#!/usr/bin/env python3
"""Generate site/assets/js/atlas-data.js from raw_data.txt (extracted from
https://bio-atlas.psu.edu/zf/progress.php on 2026-08-28)."""
import json, re, collections

PLANES = ["coronal", "sagittal", "transverse"]
PLANE_LABELS = {
    "coronal": "Coronal (dorsal to ventral)",
    "sagittal": "Sagittal (left to right)",
    "transverse": "Transverse (rostral to caudal)",
}
# Full age list in developmental order, as shown on the PSU progress page.
AGES = [
    ("24hpf",        "24hpf",        "1.9mm"),
    ("30hpf",        "30hpf",        "2.5mm"),
    ("36hpf",        "36hpf",        "2.7mm"),
    ("42hpf",        "42hpf",        "2.9mm"),
    ("48hpf",        "48hpf",        "3.1mm"),
    ("60hpf",        "60hpf",        "3.3mm"),
    ("3dpf",         "3dpf",         "3.5mm"),
    ("4dpf",         "4dpf",         "3.7mm"),
    ("5dpf",         "5dpf",         "3.9mm"),
    ("6dpf",         "6dpf",         "4.2mm"),
    ("7-13dpf",      "7-13dpf",      "4.5mm"),
    ("14-20dpf",     "14-20dpf",     "6.2mm"),
    ("21-29dpf",     "21-29dpf",     "7.8mm"),
    ("30-44dpf",     "30-44dpf",     "10mm"),
    ("45-89dpf",     "45-89dpf",     "14mm"),
    ("3mpf-male",    "3mpf male",    None),
    ("3mpf-female",  "3mpf female",  None),
    ("6mpf",         "6mpf",         None),
    ("12mpf-male",   "12mpf male",   None),
    ("12mpf-female", "12mpf female", None),
    ("18mpf",        "18mpf",        None),
    ("24mpf-male",   "24mpf male",   None),
    ("24mpf-female", "24mpf female", None),
    ("30mpf",        "30mpf",        None),
    ("36mpf",        "36mpf",        None),
]
# PSU series (atlas ids) whose slides carry anatomical annotations ("labeled series")
LABELED_ATLASES = {4, 5, 6, 72, 73}

def age_key(raw):  # "48hpf (3.1mm)" -> id
    base = raw.split(" (")[0].strip().replace(" ", "-")
    return base

rows = collections.defaultdict(lambda: {p: None for p in PLANES})
for line in open("raw_data.txt"):
    line = line.strip()
    if not line:
        continue
    age_raw, col, items = line.split("|")
    plane = PLANES[int(col)]
    slides = []
    for it in items.split(","):
        n, atlas, s = it.split(":")
        slides.append({"n": int(n), "atlas": int(atlas), "s": int(s)})
    slides.sort(key=lambda d: d["n"])
    atlas_id = slides[0]["atlas"]
    rows[age_key(age_raw)][plane] = {
        "atlas": atlas_id,
        "labeled": atlas_id in LABELED_ATLASES,
        "slides": slides,
    }

ages_out, total = [], 0
for aid, label, size in AGES:
    planes = {}
    for p in PLANES:
        series = rows.get(aid, {}).get(p)
        if series:
            total += len(series["slides"])
            planes[p] = series
    ages_out.append({"id": aid, "label": label, "size": size, "planes": planes})

data = {
    "source": "https://bio-atlas.psu.edu/zf/progress.php",
    "extracted": "2026-08-28",
    "totalSlides": total,
    "planeLabels": PLANE_LABELS,
    "ages": ages_out,
}
js = ("// Zebrafish Atlas dataset — generated by build_data.py. Do not edit by hand.\n"
      "// Source: %s (extracted %s, %d slides)\n"
      "const ATLAS_DATA = %s;\n" % (data["source"], data["extracted"], total,
                                    json.dumps(data, indent=1)))
open("site/assets/js/atlas-data.js", "w").write(js)
print("total slides:", total)
